MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 100000
    FPN_POST_NMS_TOP_N_TEST: 1000000
    NMS_THRESH: 0.4
    MIN_SIZE: 1
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH: 0.4
  ROI_BOX_HEAD:
    # NUM_CLASSES: 214
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  # TRAIN: ("shelves_train", "adapt_list")
  TRAIN: ("shelves_train", "sku_train01")
  # TRAIN: ("shelves_train")
  # TRAIN: ("shelves_train", "sku_train")
  # TRAIN: ("sku_train", )
  # TRAIN: ("sku_train10", )
  # TRAIN: ("sku_train1", )
  # TRAIN: ("sku_train01", )
  TEST: ("sku_val",)
  # TEST: ("sku_test",)
  # TEST: ("shelves_test",)
  # TEST: ("shelves_part",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
RETINANET:
  #NUM_CLASSES: 214
  NUM_CLASSES: 2
  RETINANET_ON: True
  SCALES_PER_OCTAVE: 3
  STRADDLE_THRESH: -1
  PRE_NMS_TOP_N: 10000
